{{- /*
MIT License

(C) Copyright 2022 Hewlett Packard Enterprise Development LP

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/}}

# 'wait' job that waits for hnc-controller-manager pods are up
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-hnc-manager-pods
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    metadata:
      name: wait-for-hnc-manager-pods
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      serviceAccountName: cray-hnc-manager-jobs
      containers:
        - name: wait
          image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
          imagePullPolicy: {{ .Values.kubectl.image.pullPolicy }}
          command:
            - '/bin/sh'
          args:
            - '-c'
            - 'while true; do echo "sleeping 10 seconds to ensure the deployment rollout has begun..."; sleep 10; kubectl rollout status deployment -n ${MY_POD_NAMESPACE} hnc-controller-manager; echo "sleeping 10 seconds allowing the webhook time to start..."; sleep 10; wget https://${HNC_WEBHOOK_SERVICE_SERVICE_HOST}:${HNC_WEBHOOK_SERVICE_SERVICE_PORT}/validate-v1-namespace?timeout=30s --post-data foo -S 2>&1 | grep -q SSL; if [ $? -eq 0 ]; then echo "Webhook is now responding..."; break; else echo "Webhook not responsive, sleeping 10 seconds..."; sleep 10; fi; done'
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
